target-version = "py313"
line-length = 96
indent-width = 4

[lint]
select = ["ALL"]
ignore = ["INP001", "D100", "D103", "D101", "D107", "D202", "PLR2004", "S324", "ERA001", "EM102", "TRY003", "E501"]
fixable = ["ALL"]